apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 2 # Runs two copies of your app for high availability
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        # This tells Kubernetes exactly which image to pull
        image: DOCKERHUB_USERNAME/github-actions-demo:latest
        ports:
        - containerPort: 80
