name: CI/CD Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  # ==========================================
  # JOB 1: Build the Docker Image
  # ==========================================
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Download code
        uses: actions/checkout@v4

      # Log into Docker Hub using the secure vault tokens
      - name: Step 2 - Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the image and tag it with your username and unique GitHub commit ID
      - name: Step 3 - Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:${{ github.sha }}

  # ==========================================
  # JOB 2: Deploy to Kubernetes
  # ==========================================
  deploy_to_kubernetes:
    needs: build_and_push # This tells GitHub to wait for JOB 1 to finish successfully
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
  
      # Log into Azure using your existing secrets
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
  
      # Get the connection credentials for your AKS cluster
      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group demo-rg-prod --name demo-aks-prod --overwrite-existing
  
      # Deploy the YAML file to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl rollout restart deployment/python-app-deployment
