name: CI/CD Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Download code
        uses: actions/checkout@v4

      # Log into Docker Hub using the secure vault tokens
      - name: Step 2 - Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the image and tag it with your username and unique GitHub commit ID
      - name: Step 3 - Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:${{ github.sha }}
